pipeline {
  agent any 

  stages {
    stage('Checkout') {
      steps { 
        checkout scm
      }
    }
    stage('Build') { 
      steps { 
        sh 'whoami'
        sh 'set'
        sh 'source ~/.bashrc && set'
        sh 'set'
        sh 'npm install'
      }
    }
    stage('Test'){
      steps {
        sh 'npm test'
      }
    }
  }
}

